name: Build & Deploy SK WebApp (Local Runner)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sk_webapp:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/sk_webapp:${{ github.sha }}

  deploy:
    # The build job runs on GitHub's cloud (ubuntu-latest),
    # but the deploy job will run on YOUR local VMware VM (self-hosted)
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Pull latest image from Docker Hub and deploy
        run: |
          echo "🚀 Starting deployment on self-hosted runner (VM)..."
          docker stop sk_webapp || true
          docker rm sk_webapp || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sk_webapp:latest
          docker run -d --name sk_webapp \
            -p 80:80 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/sk_webapp:latest
          docker image prune -f
          echo "✅ Deployment completed successfully!"

