name: Build & Deploy SK WebApp (Self-Hosted Runner)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sk_webapp:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/sk_webapp:${{ github.sha }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Deploy container
        run: |
          echo "🚀 Deploying SK WebApp on self-hosted VM..."
          docker stop sk_webapp || true
          docker rm sk_webapp || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sk_webapp:latest
          docker run -d --name sk_webapp \
            -p 80:80 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/sk_webapp:latest
          docker image prune -f
          echo "✅ Deployment completed!"
